name: Called

on:
    workflow_call:
        inputs:
            branch:
                description: Input string
                required: true
                type: string
                default: 'master'
            bool:
                description: Boolean input
                type: boolean
                default: false

jobs:
    called-job:
        runs-on: ubuntu-latest
        steps:
              - name: Output inputs
                run: |
                    echo "branch input: ${{ inputs.branch }}"
                    echo "Boolean input: ${{ inputs.bool }}"

              # Checkout repository
              - name: Checkout repository
                uses: actions/checkout@v5
                with:
                  ref: ${{ github.event.inputs.branch }}
                  fetch-depth: 500
                  fetch-tags: true
                  submodules: false

              # Set up Node.js
              - uses: actions/setup-node@v3
                with:
                      node-version: 22.13.1

              - name: Run Test
                run: |
                    node test.js ${{ inputs.bool }}
