name: Test My Stuff

on:
    workflow_dispatch:
        inputs:
            branch:
                description: Input branch
                required: true
                type: string
                default: 'master'
            bool:
                description: Boolean input
                type: boolean
                default: false

    schedule:
        - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
    # The default supplied using || 'staging' and || 'true' for branch and nightly
    # are in place for the scheduled run, when all inputs are null.

    test:
        uses: ./.github/workflows/sub.yml
        with:
            branch: ${{github.event.inputs.branch || 'main'}}
            bool: ${{ !contains(github.event.inputs.bool, 'false') }}
